### ISSUE TITLE
Notification Control 

### ISSUE THREAD

**Issue by Muthutc** [martijn00/XamarinMediaManager#496]
## 🐛 Bug Report

I am tried to disable Notification Control in Android but its still showing

//My code:
CrossMediaManager.Current.NotificationManager.Enabled=false;

**Expected behavior:**
Disable a Notification Manager in Android and  iOS

**Reproduction steps:**
Try to disable on Xamarin Forms running on iOS
CrossMediaManager.Current.NotificationManager.Enabled = false;

**Configuration**
Version: 0.6.1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] : Xamarin.Forms

**Comment by valentin-debris** [comment]
Hi,
As it's related to this ticket and maybe it's the source of this problem, it's actually not possible to remove the notification when stop. I mean, I want it when the song is playing but as soon as I stop the player (calling CrossMediaManager.Current.Current.Stop()), I want it to be closed (and this should be the default behavior I guess, because when we press stop on the notif, it's closed).

**Comment by valentin-debris** [comment]
@martijn00 ,
This issue seams to have bad side effect for Android. When the notif is display but the mediaPlayer is Stoped, if I close the app and reopen it, the app fails to work properly because the App object (created in MainActivity.cs by "new App()") is not clear, so when the app is reopen, I have two instances of the App and they both trigger the MessagingCenter I send.

But if I close the notification by clicking on the stop button in it, the relaunch works. 
It's like, since the Notification is visible, it blocks the Application to close properly and keep in memory.

I installed 0.6.5 and still this behavior.

**Comment by martijn00** [comment]
Should be fixed in 0.6.6

**Comment by valentin-debris** [comment]
@martijn00 ,

I tried the new version but now I have no sound ! I just switch to 0.6.6 without any changes, and playing a song does nothing. I will try to find why but if you can check that all is good from your side.

Regards

**Comment by martijn00** [comment]
@valentin-debris Some weird stuff happens on Android. Seems like a bug in exoplayer that is fixed in 2.9.6. I've made a workaround now.

**Comment by Muthutc** [comment]
Hi @martijn00  I want to disable Notification Control But its still showing.
