### ISSUE TITLE
[Android] Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by rrispoli** [martijn00/XamarinMediaManager#634]
## 🐛 Bug Report

When the video is playing and seek to some position (using SeekTo), it shows in output window this error:

```
10-25 16:29:22.618 W/SimpleExoPlayer( 4743): Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
10-25 16:29:22.618 W/SimpleExoPlayer( 4743): java.lang.IllegalStateException
10-25 16:29:22.618 W/SimpleExoPlayer( 4743): 	at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1192)
10-25 16:29:22.618 W/SimpleExoPlayer( 4743): 	at com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackParameters(SimpleExoPlayer.java:946)
```

Note that the video still working and seek to the position, but show this error.

### Expected behavior

The video seek to the position and don't show any error message.

### Reproduction steps

Play some video and when it update the progress in PositionChanged, call MediaManager.SeekTo(position).

### Configuration

**Version:** 0.8.18

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Is this still a bug?

**Comment by reshnas** [comment]
the same bug on when playing audio also

**Comment by ravikiran18** [comment]
Is this bug fixed in the latest version? Because still, I face this issue in the latest version.

**Comment by shaks786** [comment]
Any workaround for this?

**Comment by abjelosevic** [comment]
the same bug on when playing audio

**Comment by g4mb10r** [comment]
I also have this bug.  I can't play audio.

**Comment by sunsiz** [comment]
This issue still happening in the Plugin.MediaManager.Forms 1.1.1 version
When app play the local audio file from an activity on create event in the Android 7 or earlier it only play 2 second then crash, in the debug window display blow information (those from android 6 emulator, on android 7 a lot of repeated "Player is accessed on the wrong thread" message):
`[EGL_emulation] eglMakeCurrent: 0xae654660: ver 3 1 (tinfo 0xae652b60)
[SimpleExoPlayer] Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
[SimpleExoPlayer]   java.lang.IllegalStateException
[SimpleExoPlayer]       at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1575)
[SimpleExoPlayer]       at com.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:1281)
[SimpleExoPlayer] Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
[EGL_emulation] eglMakeCurrent: 0xae654660: ver 3 1 (tinfo 0xae652b60)
[Surface] getSlotFromBufferLocked: unknown buffer: 0x99efbba0`
But the same file play with a button to test sound, it plays without problem.
